# Generated by Django 5.0.1 on 2024-02-29 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('Marca', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('novo', models.BooleanField(default=False)),
                ('sinistros', models.TextField()),
                ('slug', models.SlugField()),
                ('condutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.condutor')),
            ],
        ),
    ]
